### ISSUE TITLE
is it possible adding a mysql_option timeout ?

### ISSUE THREAD

**Issue by TheSnowFox** [IBM-Swift/SwiftKueryMySQL#13]
Hi,
First of all, thank you very much for this module and SwiftKuery, you've done an great job.
I'm using your modules for my current project and it works great except for one thing: 
At the first connection, if mysql server is down or if settings are wrong (host address, password, etc.) in:
`MySQLThreadSafeConnection.createPool(host: , user: , password: , database: , port: , unixSocket: , clientFlag: , characterSet:, reconnect:, poolOptions: )` ,
the execution is blocked at: 
`if mysql_real_connect(mysql, host, user, password, database, port, unixSocket, clientFlag) != nil`  in connect() (line 166 in MySQLConnection.swift)
The program doesn't crash  but seems waiting.

I can be wrong but by reading the source files, it seems that `mysql_options(MYSQL_OPT_CONNECT_TIMEOUT)` was never set.
Is it possible to add a way to set this property or using timeout argument in `ConnectionPoolOption(initialCapacity:, maxCapacity:, timeout:)` ?

Thank you in advance

**Comment by ianpartridge** [comment]
That sounds like a good enhancement and we would definitely welcome a PR to improve this.

**Comment by TheSnowFox** [comment]
Sorry for my latency, I thought I would receive a notification by mail...
I'm new to gitHub, and not a professional developper (this is not my main activity...)
PR stands for pull request ?

I forked the repository and modify the file, pushed to the new fork. Tell me if you want me to try a pull request... I don't exactly know the procedure and how to tag version... (it has changed from 0.13.2 to 1.0.0 ?)

**Comment by ianpartridge** [comment]
Yes, PR is Pull Request. I took a look at your fork commit at https://github.com/TheSnowFox/SwiftKueryMySQL/commit/da372d59d53faea1d2255990dab235afa4f5682b it looks ready for review.

You should be able to open the PR by going to https://github.com/TheSnowFox/SwiftKueryMySQL and clicking the "New Pull Request" button.

**Comment by TheSnowFox** [comment]
Thank you :)
I've just tried
