### ISSUE TITLE
Use of unresolved identifier 'MYSQL_TYPE_JSON'

### ISSUE THREAD

**Issue by ChristopherCarranza** [IBM-Swift/SwiftKueryMySQL#2]
Getting some build errors when trying to use `SwiftKueryMySQL`. Screenshot pictured below shows the error `use of unresolved identifier 'MYSQL_TYPE_JSON'`. Using Swift 3.1 / Xcode 8.1, and the package file is shown below as well. Have MySQL installed on macOS Sierra. Have it linked via the instructions but still nothing. Same error when building via Xcode or terminal. Imagine its something with my MySQL install or maybe the version?

```swift
import PackageDescription

let package = Package(
    name: "my-app",
	dependencies: [
    .Package(url: "https://github.com/IBM-Swift/HeliumLogger.git", majorVersion: 1, minor: 7),
    .Package(url: "https://github.com/IBM-Swift/Kitura.git", majorVersion: 1, minor: 7),
    .Package(url: "https://github.com/IBM-Swift/Kitura-StencilTemplateEngine.git", majorVersion: 1, minor: 8),
    .Package(url: "https://github.com/IBM-Swift/CloudConfiguration.git", majorVersion: 2),
    .Package(url: "https://github.com/johnsundell/unbox.git", majorVersion: 2, minor: 4),
    .Package(url: "https://github.com/IBM-Swift/SwiftKueryMySQL.git", majorVersion: 0, minor: 11)
	]
)
```

<img width="851" alt="screen shot 2017-05-17 at 10 14 09 am" src="https://cloud.githubusercontent.com/assets/4485800/26162549/abb4dc94-3aec-11e7-8b91-805bf417adf2.png">

**Comment by na-gupta** [comment]
@ChristopherCarranza I believe `MYSQL_TYPE_JSON` was introduced in MySQL v5.7
Your MySQL install is probably older than 5.7 and upgrading it should fix the issue.

**Comment by ChristopherCarranza** [comment]
@na-gupta That was the problem! Thank you! Maybe adding the minimum MySQL version in the readme?

**Comment by na-gupta** [comment]
@ChristopherCarranza I have added that to the readme. Thanks!

**Comment by ChristopherCarranza** [comment]
This might be little outside the scope of this issue, but i get similar compile issues when deploying to the Bluemix platform with a connected Compose MySQL service. Not sure if you have any ideas or should i direct this to their support people.

```
 MYSQL_TYPE_JSON:
       public var MYSQL_TYPE_BLOB: enum_field_types { get }
                  ^
       CmySQLlinux.MYSQL_TYPE_LONG:1:12: note: did you mean 'MYSQL_TYPE_LONG'?
       CmySQLlinux.MYSQL_TYPE_SET:1:12: note: did you mean 'MYSQL_TYPE_SET'?
       public var MYSQL_TYPE_SET: enum_field_types { get }
<unknown>:0: error: build had 1 command failures
Failed to compile droplet
Exit status 223
``

**Comment by na-gupta** [comment]
@ChristopherCarranza  I removed the MYSQL_TYPE_JSON reference so it's picked up in the default case for 5.7, but now allows it to run on 5.5. Please pull the latest tag and try again. Thanks.

**Comment by ChristopherCarranza** [comment]
@na-gupta that worked! Compiles just fine, thanks again!
