### ISSUE TITLE
Ignoring declared target(s) 'CMySQL' in the system package

### ISSUE THREAD

**Issue by sglushchenko** [IBM-Swift/SwiftKueryMySQL#39]
Hello guys,
I can't find a solution to my issue. I can't compile a project with mysql.

I have warning
`Ignoring declared target(s) 'CMySQL' in the system package`
And
`ld: warning: Could not find auto-linked library 'mysqlclient'`

How I understand CMySQL connect mysql c library.

I use Swift 4.2 on mac os
I installed mysql 5.7. When I use Perfect framework it connected and work. I can work with mysql from the command line.
I made steps like in this issue #12  and steps in instructions.

my log:

```
swift build
'CMySQL' /Users/sglushchenko/Projects/Monopoly/Activities/.build/checkouts/CMySQL.git--8159864709556537942: warning: Ignoring declared target(s) 'CMySQL' in the system package
Linking ./.build/x86_64-apple-macosx10.10/debug/Activities
ld: warning: Could not find auto-linked library 'mysqlclient'
Undefined symbols for architecture x86_64:
  "_mysql_character_set_name", referenced from:
      _$S15SwiftKueryMySQL0C13SQLConnectionC7connect12onCompletionyy0aB010QueryErrorOSgXE_tF in MySQLConnection.swift.o
  "_mysql_close", referenced from:
      _$S15SwiftKueryMySQL0C13SQLConnectionC15closeConnectionyyF in MySQLConnection.swift.o
  "_mysql_errno", referenced from:
      _$S15SwiftKueryMySQL0C13SQLConnectionC7connect12onCompletionyy0aB010QueryErrorOSgXE_tF in MySQLConnection.swift.o
      _$S15SwiftKueryMySQL0C13SQLConnectionC8getErrorySSSpySo8st_mysqlVGFZ in MySQLConnection.swift.o
  "_mysql_error", referenced from:
      _$S15SwiftKueryMySQL0C13SQLConnectionC8getErrorySSSpySo8st_mysqlVGFZ in MySQLConnection.swift.o
  "_mysql_fetch_fields", referenced from:
      _$S15SwiftKueryMySQL0C16SQLResultFetcherC17preparedStatement14resultMetadataAcA0c11SQLPreparedH0C_SpySo12st_mysql_resVGtKcfc in MySQLResultFetcher.swift.o
  "_mysql_free_result", referenced from:
      _$S15SwiftKueryMySQL0C20SQLPreparedStatementC7execute10parameters12onCompletionySayypSgGSg_y0aB011QueryResultOctF6$deferL_yyF in MySQLPreparedStatement.swift.o
  "_mysql_init", referenced from:
      _$S15SwiftKueryMySQL0C13SQLConnectionC7connect12onCompletionyy0aB010QueryErrorOSgXE_tF in MySQLConnection.swift.o
  "_mysql_num_fields", referenced from:
      _$S15SwiftKueryMySQL0C16SQLResultFetcherC17preparedStatement14resultMetadataAcA0c11SQLPreparedH0C_SpySo12st_mysql_resVGtKcfc in MySQLResultFetcher.swift.o
  "_mysql_options", referenced from:
      _$S15SwiftKueryMySQL0C13SQLConnectionC7connect12onCompletionyy0aB010QueryErrorOSgXE_tFySPys4Int8VGXEfU_ in MySQLConnection.swift.o
      _$S15SwiftKueryMySQL0C13SQLConnectionC7connect12onCompletionyy0aB010QueryErrorOSgXE_tFySPySuGXEfU0_ in MySQLConnection.swift.o
     (maybe you meant: _$SSo16st_mysql_optionsV18__Unnamed_union_ciVMB, _$SSo16st_mysql_optionsV18__Unnamed_union_ciVMF , _$SSo16st_mysql_optionsV18__Unnamed_union_ciVMn , _$SSo16st_mysql_optionsVWV , _symbolic So16st_mysql_optionsV18__Unnamed_union_ciV , _symbolic So16st_mysql_optionsV , _$SSo16st_mysql_optionsV18__Unnamed_union_ciVN , _$SSo16st_mysql_optionsV18__Unnamed_union_ciVML , _$SSo16st_mysql_optionsV18__Unnamed_union_ciVMa , _$SSo16st_mysql_optionsVwet , _$SSo16st_mysql_optionsVwCP , _$SSo16st_mysql_optionsVN , _$SSo16st_mysql_optionsVML , _$SSo16st_mysql_optionsVMa , _$SSo16st_mysql_optionsVMB , _$SSo16st_mysql_optionsVMn , _$SSo16st_mysql_optionsVwst , _$SSo16st_mysql_optionsVMF )
  "_mysql_ping", referenced from:
      _$S15SwiftKueryMySQL0C13SQLConnectionC11isConnectedSbvg in MySQLConnection.swift.o
  "_mysql_query", referenced from:
      _$S15SwiftKueryMySQL0C13SQLConnectionC18executeTransaction7command02inG006changeG5State12errorMessage12onCompletionySS_S2bSSy0aB011QueryResultOctF in MySQLConnection.swift.o
  "_mysql_real_connect", referenced from:
      _$S15SwiftKueryMySQL0C13SQLConnectionC7connect12onCompletionyy0aB010QueryErrorOSgXE_tF in MySQLConnection.swift.o
  "_mysql_server_init", referenced from:
      _$S15SwiftKueryMySQL0C13SQLConnectionC8initOnce33_6965988EF4E4584ED9366C61FD57FE5DLLytvpZfiyyXEfU_ in MySQLConnection.swift.o
  "_mysql_set_character_set", referenced from:
      _$S15SwiftKueryMySQL0C13SQLConnectionC7connect12onCompletionyy0aB010QueryErrorOSgXE_tF in MySQLConnection.swift.o
  "_mysql_stmt_affected_rows", referenced from:
      _$S15SwiftKueryMySQL0C20SQLPreparedStatementC7execute10parameters12onCompletionySayypSgGSg_y0aB011QueryResultOctF in MySQLPreparedStatement.swift.o
  "_mysql_stmt_bind_param", referenced from:
      _$S15SwiftKueryMySQL0C20SQLPreparedStatementC13allocateBinds33_24A6EC5E18CE7BDEF835DAEBCD43F449LL10parametersySayypSgG_tKF in MySQLPreparedStatement.swift.o
  "_mysql_stmt_bind_result", referenced from:
      _$S15SwiftKueryMySQL0C16SQLResultFetcherC17preparedStatement14resultMetadataAcA0c11SQLPreparedH0C_SpySo12st_mysql_resVGtKcfc in MySQLResultFetcher.swift.o
  "_mysql_stmt_close", referenced from:
      _$S15SwiftKueryMySQL0C20SQLPreparedStatementC_5query5mysqlACSS_0aB05Query_pSgSpySo03st_H0VGSgtKcfc6$deferL_yyF in MySQLPreparedStatement.swift.o
      _$S15SwiftKueryMySQL0C20SQLPreparedStatementC7releaseyyF in MySQLPreparedStatement.swift.o
      _$S15SwiftKueryMySQL0C20SQLPreparedStatementC7execute10parameters12onCompletionySayypSgGSg_y0aB011QueryResultOctF in MySQLPreparedStatement.swift.o
      _$S15SwiftKueryMySQL0C20SQLPreparedStatementC11handleError33_24A6EC5E18CE7BDEF835DAEBCD43F449LL12onCompletionyy0aB011QueryResultOc_tF in MySQLPreparedStatement.swift.o
  "_mysql_stmt_errno", referenced from:
      _$S15SwiftKueryMySQL0C13SQLConnectionC8getErrorySSSpySo13st_mysql_stmtVGFZ in MySQLConnection.swift.o
  "_mysql_stmt_error", referenced from:
      _$S15SwiftKueryMySQL0C13SQLConnectionC8getErrorySSSpySo13st_mysql_stmtVGFZ in MySQLConnection.swift.o
  "_mysql_stmt_execute", referenced from:
      _$S15SwiftKueryMySQL0C20SQLPreparedStatementC7execute10parameters12onCompletionySayypSgGSg_y0aB011QueryResultOctF in MySQLPreparedStatement.swift.o
      _$S15SwiftKueryMySQL0C16SQLResultFetcherC17preparedStatement14resultMetadataAcA0c11SQLPreparedH0C_SpySo12st_mysql_resVGtKcfc in MySQLResultFetcher.swift.o
  "_mysql_stmt_fetch", referenced from:
      _$S15SwiftKueryMySQL0C16SQLResultFetcherC8buildRow33_A5E6888CAFD2A8813D5EADC1F84A5417LLSayypSgGSgyF in MySQLResultFetcher.swift.o
  "_mysql_stmt_init", referenced from:
      _$S15SwiftKueryMySQL0C20SQLPreparedStatementC_5query5mysqlACSS_0aB05Query_pSgSpySo03st_H0VGSgtKcfc in MySQLPreparedStatement.swift.o
  "_mysql_stmt_prepare", referenced from:
      _$S15SwiftKueryMySQL0C20SQLPreparedStatementC_5query5mysqlACSS_0aB05Query_pSgSpySo03st_H0VGSgtKcfc in MySQLPreparedStatement.swift.o
  "_mysql_stmt_result_metadata", referenced from:
      _$S15SwiftKueryMySQL0C20SQLPreparedStatementC7execute10parameters12onCompletionySayypSgGSg_y0aB011QueryResultOctF in MySQLPreparedStatement.swift.o
  "_mysql_thread_end", referenced from:
      _$S15SwiftKueryMySQL0C13SQLConnectionC7connect12onCompletionyy0aB010QueryErrorOSgXE_tF in MySQLConnection.swift.o
      _$S15SwiftKueryMySQL0C13SQLConnectionC15closeConnectionyyF in MySQLConnection.swift.o
ld: symbol(s) not found for architecture x86_64
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
```

**Comment by fabrijp** [comment]
@kilnerm still the same.
`..build/checkouts/CMySQL.git--4740587909601729142: warning: Ignoring declared target(s) 'CMySQL' in the system package`

**Comment by kilnerm** [comment]
@fabrijp, Which version of SwiftKueryMySQL are you using?

Do you also see the compilation errors?

**Comment by fabrijp** [comment]
@kilnerm I'm using SwiftKueryMySQL 1.2.0 and it show the errors below. I just created a new project with `kitura init` command and added the SwiftKueryMySQL on the Package.swift

`..build/checkouts/CMySQL.git--8816392111242171006: warning: Ignoring declared target(s) 'CMySQL' in the system package
Linking ./.build/x86_64-apple-macosx10.10/debug/AuthenProxy
ld: warning: Could not find auto-linked library 'mysqlclient'
Undefined symbols for architecture x86_64:
  "_$S16CloudEnvironment0A3EnvC16mappingsFilePath012cloudFoundryE0ACSSSg_AFtcfC", referenced from:
      _$S11Application3AppC8cloudEnv16CloudEnvironment0eD0Cvpfi in Application.swift.o
      _$S11Application3AppCACyKcfc in Application.swift.o
  "_$S16CloudEnvironment0A3EnvCMa", referenced from:
      _$S11Application3AppC8cloudEnv16CloudEnvironment0eD0Cvpfi in Application.swift.o
      _$S11Application3AppCACyKcfc in Application.swift.o
  "_mysql_character_set_name", referenced from:
      _$S15SwiftKueryMySQL0C13SQLConnectionC7connect12onCompletionyy0aB010QueryErrorOSgXE_tF in MySQLConnection.swift.o
  "_mysql_close", referenced from:
      _$S15SwiftKueryMySQL0C13SQLConnectionC15closeConnectionyyF in MySQLConnection.swift.o
  "_mysql_errno", referenced from:
      _$S15SwiftKueryMySQL0C13SQLConnectionC7connect12onCompletionyy0aB010QueryErrorOSgXE_tF in MySQLConnection.swift.o
      _$S15SwiftKueryMySQL0C13SQLConnectionC8getErrorySSSpySo8st_mysqlVGFZ in MySQLConnection.swift.o
  "_mysql_error", referenced from:
      _$S15SwiftKueryMySQL0C13SQLConnectionC8getErrorySSSpySo8st_mysqlVGFZ in MySQLConnection.swift.o
  "_mysql_fetch_fields", referenced from:
      _$S15SwiftKueryMySQL0C16SQLResultFetcherC17preparedStatement14resultMetadataAcA0c11SQLPreparedH0C_SpySo12st_mysql_resVGtKcfc in MySQLResultFetcher.swift.o
  "_mysql_free_result", referenced from:
      _$S15SwiftKueryMySQL0C20SQLPreparedStatementC7execute10parameters12onCompletionySayypSgGSg_y0aB011QueryResultOctF6$deferL_yyF in MySQLPreparedStatement.swift.o
  "_mysql_init", referenced from:
      _$S15SwiftKueryMySQL0C13SQLConnectionC7connect12onCompletionyy0aB010QueryErrorOSgXE_tF in MySQLConnection.swift.o
  "_mysql_num_fields", referenced from:
      _$S15SwiftKueryMySQL0C16SQLResultFetcherC17preparedStatement14resultMetadataAcA0c11SQLPreparedH0C_SpySo12st_mysql_resVGtKcfc in MySQLResultFetcher.swift.o
  "_mysql_options", referenced from:
      _$S15SwiftKueryMySQL0C13SQLConnectionC7connect12onCompletionyy0aB010QueryErrorOSgXE_tFySPys4Int8VGXEfU_ in MySQLConnection.swift.o
      _$S15SwiftKueryMySQL0C13SQLConnectionC7connect12onCompletionyy0aB010QueryErrorOSgXE_tFySPySuGXEfU0_ in MySQLConnection.swift.o
     (maybe you meant: _$SSo16st_mysql_optionsV18__Unnamed_union_ciVMF, _$SSo16st_mysql_optionsV18__Unnamed_union_ciVMn , _$SSo16st_mysql_optionsVWV , _symbolic So16st_mysql_optionsV18__Unnamed_union_ciV , _symbolic So16st_mysql_optionsV , _$SSo16st_mysql_optionsV18__Unnamed_union_ciVN , _$SSo16st_mysql_optionsV18__Unnamed_union_ciVML , _$SSo16st_mysql_optionsV18__Unnamed_union_ciVMa , _$SSo16st_mysql_optionsVwet , _$SSo16st_mysql_optionsVwCP , _$SSo16st_mysql_optionsVN , _$SSo16st_mysql_optionsVML , _$SSo16st_mysql_optionsVMa , _$SSo16st_mysql_optionsVMB , _$SSo16st_mysql_optionsVMn , _$SSo16st_mysql_optionsVwst , _$SSo16st_mysql_optionsVMF , _$SSo16st_mysql_optionsV18__Unnamed_union_ciVMB )
  "_mysql_ping", referenced from:
      _$S15SwiftKueryMySQL0C13SQLConnectionC11isConnectedSbvg in MySQLConnection.swift.o
  "_mysql_query", referenced from:
      _$S15SwiftKueryMySQL0C13SQLConnectionC18executeTransaction7command02inG006changeG5State12errorMessage12onCompletionySS_S2bSSy0aB011QueryResultOctF in MySQLConnection.swift.o
  "_mysql_real_connect", referenced from:
      _$S15SwiftKueryMySQL0C13SQLConnectionC7connect12onCompletionyy0aB010QueryErrorOSgXE_tF in MySQLConnection.swift.o
  "_mysql_server_init", referenced from:
      _$S15SwiftKueryMySQL0C13SQLConnectionC8initOnce33_6965988EF4E4584ED9366C61FD57FE5DLLytvpZfiyyXEfU_ in MySQLConnection.swift.o
  "_mysql_set_character_set", referenced from:
      _$S15SwiftKueryMySQL0C13SQLConnectionC7connect12onCompletionyy0aB010QueryErrorOSgXE_tF in MySQLConnection.swift.o
  "_mysql_stmt_affected_rows", referenced from:
      _$S15SwiftKueryMySQL0C20SQLPreparedStatementC7execute10parameters12onCompletionySayypSgGSg_y0aB011QueryResultOctF in MySQLPreparedStatement.swift.o
  "_mysql_stmt_bind_param", referenced from:
      _$S15SwiftKueryMySQL0C20SQLPreparedStatementC13allocateBinds33_24A6EC5E18CE7BDEF835DAEBCD43F449LL10parametersySayypSgG_tKF in MySQLPreparedStatement.swift.o
  "_mysql_stmt_bind_result", referenced from:
      _$S15SwiftKueryMySQL0C16SQLResultFetcherC17preparedStatement14resultMetadataAcA0c11SQLPreparedH0C_SpySo12st_mysql_resVGtKcfc in MySQLResultFetcher.swift.o
  "_mysql_stmt_close", referenced from:
      _$S15SwiftKueryMySQL0C20SQLPreparedStatementC_5query5mysqlACSS_0aB05Query_pSgSpySo03st_H0VGSgtKcfc6$deferL_yyF in MySQLPreparedStatement.swift.o
      _$S15SwiftKueryMySQL0C20SQLPreparedStatementC7releaseyyF in MySQLPreparedStatement.swift.o
      _$S15SwiftKueryMySQL0C20SQLPreparedStatementC7execute10parameters12onCompletionySayypSgGSg_y0aB011QueryResultOctF in MySQLPreparedStatement.swift.o
      _$S15SwiftKueryMySQL0C20SQLPreparedStatementC11handleError33_24A6EC5E18CE7BDEF835DAEBCD43F449LL12onCompletionyy0aB011QueryResultOc_tF in MySQLPreparedStatement.swift.o
  "_mysql_stmt_errno", referenced from:
      _$S15SwiftKueryMySQL0C13SQLConnectionC8getErrorySSSpySo13st_mysql_stmtVGFZ in MySQLConnection.swift.o
  "_mysql_stmt_error", referenced from:
      _$S15SwiftKueryMySQL0C13SQLConnectionC8getErrorySSSpySo13st_mysql_stmtVGFZ in MySQLConnection.swift.o
  "_mysql_stmt_execute", referenced from:
      _$S15SwiftKueryMySQL0C20SQLPreparedStatementC7execute10parameters12onCompletionySayypSgGSg_y0aB011QueryResultOctF in MySQLPreparedStatement.swift.o
      _$S15SwiftKueryMySQL0C16SQLResultFetcherC17preparedStatement14resultMetadataAcA0c11SQLPreparedH0C_SpySo12st_mysql_resVGtKcfc in MySQLResultFetcher.swift.o
  "_mysql_stmt_fetch", referenced from:
      _$S15SwiftKueryMySQL0C16SQLResultFetcherC8buildRow33_A5E6888CAFD2A8813D5EADC1F84A5417LLSayypSgGSgyF in MySQLResultFetcher.swift.o
  "_mysql_stmt_init", referenced from:
      _$S15SwiftKueryMySQL0C20SQLPreparedStatementC_5query5mysqlACSS_0aB05Query_pSgSpySo03st_H0VGSgtKcfc in MySQLPreparedStatement.swift.o
  "_mysql_stmt_prepare", referenced from:
      _$S15SwiftKueryMySQL0C20SQLPreparedStatementC_5query5mysqlACSS_0aB05Query_pSgSpySo03st_H0VGSgtKcfc in MySQLPreparedStatement.swift.o
  "_mysql_stmt_result_metadata", referenced from:
      _$S15SwiftKueryMySQL0C20SQLPreparedStatementC7execute10parameters12onCompletionySayypSgGSg_y0aB011QueryResultOctF in MySQLPreparedStatement.swift.o
  "_mysql_thread_end", referenced from:
      _$S15SwiftKueryMySQL0C13SQLConnectionC7connect12onCompletionyy0aB010QueryErrorOSgXE_tF in MySQLConnection.swift.o
      _$S15SwiftKueryMySQL0C13SQLConnectionC15closeConnectionyyF in MySQLConnection.swift.o
ld: symbol(s) not found for architecture x86_64`

**Comment by sglushchenko** [comment]
@kilnerm I see that you have Package@4.0.swift, Package@4.1.swift. Maybe we should have Package@4.2.swift? And using a system module library is deprecated.
But, If I setup dependencies to `https://github.com/vapor/cmysql.git`, I don't have a problem with a CMySQL or mysqlclient.

But I have freeze when I try to build the code and package manager try update CURL library :). It looks like endless loop

**Comment by kilnerm** [comment]
For Swift 4.2 it would default to the Package.swift file which has an appropriate format. This however is only presently available in the next branch (which is what you will see by default).

Let me see if I can reproduce the problem to confirm what I suspect is happening.

**Comment by sglushchenko** [comment]
@kilnerm And I use MacOS Mojave, I haven't tried it on Linux. Maybe it helps

**Comment by sglushchenko** [comment]
@kilnerm It works with the linker. Will you add it to Readme or will you fix it with a new commit?

**Comment by kilnerm** [comment]
It's already in the readme for the master branch and at the latest release tag level. I'm a little torn here, the obvious solution is that we just make master the default branch again but that comes with the issue that anyone contributing fixes may be basing their fix on out of date code as everything planned for the next release is in the next branch. 

I need to have a conversation with some colleagues before I can say how the issue will be addressed. Once we have a solution I'll update here.

**Comment by sglushchenko** [comment]
@kilnerm Thank you :)

**Comment by fabrijp** [comment]
Thanks @kilnerm I got it to work with MySQL 5.7 using the linker flag. Just to note the linker doesn't work with MySQL 8 that is the default version for brew installation.

**Comment by kilnerm** [comment]
@fabrijp, There are changes coming in the next release that will remove the need for the compiler flags and provide support for mysql 8.

**Comment by fabrijp** [comment]
Great ! Thank you @kilnerm

**Comment by kilnerm** [comment]
Following the release of SwiftKuery 3.0 we will revert back to using master as the default branch.

**Comment by kilnerm** [comment]
We released SwiftKuery 3 in late December, the repositories default branch has been switched back to master so the default Readme reflects the current instructions for using MySQL.

I am marking this as closed, if there are any further questions please re-open as needed.
