### ISSUE TITLE
SwiftKuery 0.12.X Support

### ISSUE THREAD

**Issue by ChristopherCarranza** [IBM-Swift/SwiftKueryMySQL#4]
Any chance we can get this to be compatible with SwiftKuery 0.12.X. I'd like to use the Schema management of 0.12, but this is still using 0.11. Thanks.

**Comment by na-gupta** [comment]
Yes, we plan to get that in a day or two.

**Comment by na-gupta** [comment]
Support for this is now available in SwiftKueryMySQL-0.12
