### ISSUE TITLE
MySQL error when building SwiftKueryMySQL 2.0/SwiftKuery 3.0 in Docker image

### ISSUE THREAD

**Issue by rtvanals** [IBM-Swift/SwiftKueryMySQL#48]
I updated my package to SwiftKuery 2.0, made the necessary migrations to my code and tried to deploy in Docker and have an issue that wasn't there before.

```Compile Swift Module 'SwiftKueryMySQL' (3 sources)
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "shim.h"
         ^
/root/MyProject/.build/checkouts/SwiftKueryMySQL.git--3836254919944530584/Sources/CMySQL/shim.h:3:10: error: 'mysql.h' file not found
#include <mysql.h>
         ^
/root/MyProject/.build/checkouts/SwiftKueryMySQL.git--3836254919944530584/Sources/SwiftKueryMySQL/MySQLConnection.swift:21:8: error: could not build C module 'CMySQL'
import CMySQL
       ^
```

Here is my Dockerfile:

```
FROM ibmcom/swift-ubuntu:latest
MAINTAINER Me
LABEL Description="My Docker"

# Update packages list
RUN apt-get update

# Install common packages
RUN apt-get install -y --no-install-recommends \
        git 

RUN apt-get install -y --no-install-recommends mysql-server libmysqlclient-dev

EXPOSE 8080

RUN mkdir /root/MyProject

ADD Project/Sources /root/MyProject
ADD Project/Package.swift /root/MyProject


# Build
RUN cd /root/MyProject && swift build -c release -Xlinker -L/usr/local/lib

# Run
USER root
CMD ["/root/MyProject/.build/release/Server"]
```

Is there some configuration that I need to update?

**Comment by rtvanals** [comment]
Ok.  I found the answer.  I had to change the build command in the Dockerfile to:

`RUN cd /root/MyProject && swift build -c release -Xlinker -L/usr/local/lib -Xcc -I/usr/include/mysql/`

**Comment by Ram-Muljani** [comment]
I am getting this error. I am using Mac OS with Kitura Studio. I am building from kitura studio. I tried everything to resolve this, Not sure what to do next. Please help


<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "shim.h"
         ^
/Users/RamMuljani/Scade/mykituraapp/.build/checkouts/SwiftKueryMySQL.git--4551972435165752597/Sources/CMySQL/shim.h:3:10: error: 'mysql.h' file not found
#include <mysql.h>
         ^
/Users/RamMuljani/Scade/mykituraapp/.build/checkouts/SwiftKueryMySQL.git--4551972435165752597/Sources/SwiftKueryMySQL/MySQLConnection.swift:21:8: error: could not build C module 'CMySQL'
import CMySQL
       ^
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "shim.h"
         ^
/Users/RamMuljani/Scade/mykituraapp/.build/checkouts/SwiftKueryMySQL.git--4551972435165752597/Sources/CMySQL/shim.h:3:10: error: 'mysql.h' file not found
#include <mysql.h>
         ^
/Users/RamMuljani/Scade/mykituraapp/.build/checkouts/SwiftKueryMySQL.git--4551972435165752597/Sources/SwiftKueryMySQL/MySQLConnection.swift:21:8: error: could not build C module 'CMySQL'
import CMySQL
       ^
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "shim.h"
         ^
/Users/RamMuljani/Scade/mykituraapp/.build/checkouts/SwiftKueryMySQL.git--4551972435165752597/Sources/CMySQL/shim.h:3:10: error: 'mysql.h' file not found
#include <mysql.h>
         ^
/Users/RamMuljani/Scade/mykituraapp/.build/checkouts/SwiftKueryMySQL.git--4551972435165752597/Sources/SwiftKueryMySQL/MySQLConnection.swift:21:8: error: could not build C module 'CMySQL'
import CMySQL
       ^
error: terminated(1): /usr/bin/swift-build-tool -f /Users/RamMuljani/Scade/mykituraapp/.build/debug.yaml main -v output:
