### ISSUE TITLE
Can't set NULL to nullable column

### ISSUE THREAD

**Issue by sglushchenko** [IBM-Swift/SwiftKueryMySQL#49]
Hello,
I can't set NULL to any fields. for example, I have a token in user, when the token is expired I would like to set NULL to this field. I can't make it now.

Can you explain how I can make it without a raw query?

I think need to support NSNull, if it supported in Linux or similar type.

And result code will be like:
Insert(into: table, columns: [table.token], values: [NSNull]).execute....

**Comment by kilnerm** [comment]
@sglushchenko, Can you share your definition of your User table? Thanks.

**Comment by sglushchenko** [comment]
I think it doesn't matter. It can be any table. for example:
```
class FeatureRequestTable_V0: Table {
    let tableName = "feature_request"
    let id = Column("id", Varchar.self, length: 36, autoIncrement: false, primaryKey: true, notNull: true, unique: true, defaultValue: nil, check: nil, collate: nil)
    let userId = Column("user_id", String.self)
    let subject = Column("subject", String.self)
    let email = Column("email", String.self)
    let text = Column("text", String.self)
    let state = Column("state", String.self)
    let createdAt = Column("created_at", Int32.self)
    let updatedAt = Column("updated_at", Int32.self)
}
```
How I can set `email` to NULL?
Thanks.

**Comment by kilnerm** [comment]
We have merged a change that will allow for `nil` to be converted to `NULL` for insertion into the database.

Some further changes are needed to remove compile warnings when using this capability and to support `nil` default values on a `Column`.

I'll pull together a PR to round out the `nil` support.

**Comment by kilnerm** [comment]
I have opened https://github.com/IBM-Swift/Swift-Kuery/pull/177 to round out the nil support.
