### ISSUE TITLE
macOS Failed to retrieve search path with pkg-config

### ISSUE THREAD

**Issue by Beautylivery** [IBM-Swift/SwiftKueryMySQL#62]
Hello,

after setting up a fresh Kitura init and i added the SwiftKueryMySQL package, i received the following message while generating the xcodeproj.

Cloning https://github.com/IBM-Swift/Swift-Kuery.git
Resolving https://github.com/IBM-Swift/Swift-Kuery.git at 3.0.1
warning: failed to retrieve search paths with pkg-config; maybe pkg-config is not installed

Is there a dependency i am not aware of ?
Here are some further details... on the package

// swift-tools-version:5.0
import PackageDescription

let package = Package(
    name: "Beautylivery_Server_New",
    dependencies: [
      .package(url: "https://github.com/IBM-Swift/Kitura.git", .upToNextMinor(from: "2.7.0")),
      .package(url: "https://github.com/IBM-Swift/HeliumLogger.git", from: "1.7.1"),
      .package(url: "https://github.com/IBM-Swift/CloudEnvironment.git", from: "9.0.0"),
      .package(url: "https://github.com/RuntimeTools/SwiftMetrics.git", from: "2.0.0"),
      .package(url: "https://github.com/IBM-Swift/Health.git", from: "1.0.0"),
      .package(url: "https://github.com/IBM-Swift/SwiftKueryMySQL.git", from: "2.0.2"),

    ],
    targets: [
      .target(name: "Beautylivery_Server_New", dependencies: [ .target(name: "Application"), "Kitura" , "HeliumLogger", "SwiftKueryMySQL"]),
      .target(name: "Application", dependencies: [ "Kitura", "CloudEnvironment","SwiftMetrics", "Health", 

      ]),

      .testTarget(name: "ApplicationTests" , dependencies: [.target(name: "Application"), "Kitura","HeliumLogger" ])
    ]
)

**Comment by kilnerm** [comment]
@Beautylivery SwiftKueryMySQL relies upon pkg-config to determine the library and header paths that are needed to link to it's C library.

Do you have pkg-config installed? (Check the output from pkg-config --version)

**Comment by Beautylivery** [comment]
yeah seems to be the issue ! . Thanks
