### ISSUE TITLE
Add support for Kuery 4.0+

### ISSUE THREAD

**Issue by JxD-DeciSion** [IBM-Swift/SwiftKueryMySQL#71]
I can't use this package with my swift 5.6 env. Compiler is giving me an error as following:

```
error: Dependencies could not be resolved because root depends on 'swift-kuery' 4.0.0..<5.0.0 and root depends on 'swiftkuerymysql' 2.0.2..<3.0.0.
'swiftkuerymysql' >= 2.0.2 practically depends on 'swift-kuery' 3.0.0..<4.0.0 because 'swiftkuerymysql' 2.0.2 depends on 'swift-kuery' 3.0.0..<4.0.0.
```

Since Swift-Kuery 4.0.0+ is needed with swift5 ([ambiguity issue](https://github.com/Kitura/Swift-Kuery/pull/203)) this package is basically not compatible with swift 5. Same goes for the other SQL packages iirc.

Maybe I'm wrong, but I'm dealing with this issue for days now and couldn't manage to get a workaround myself.

**Comment by JxD-DeciSion** [comment]
Ah nvm. You just need to use master-branch for Swift-Kuery, my bad and thank you guys anyways.

**Comment by dannys42** [comment]
@JxD-DeciSion, glad you have a workaround with master.  I'll keep this on my list to make sure there's an actual release that works, though.
