### ISSUE TITLE
Real connection status

### ISSUE THREAD

**Issue by russanto** [IBM-Swift/SwiftKueryMySQL#9]
From the MySQLConnection isn't possible to access the real mysql connection status. The isConnected property only relies on the presence of a reference to the MYSQL object given by C connector. This makes all the package unusable unless you don't create a new connection each time it's needed. In fact it's not possible to know if the connection has been closed for some other reason that aren't in control of Swift server. For example in my case MySql server drops the connection after a period of inactivity, but the pool of connection provided gives the connection basing the choice only on a mutual exclusion rule.

**Comment by na-gupta** [comment]
@russanto Fixed in 0.13.1 . Thanks.
